<?php

namespace CodePress\CodeCategory\Tests;

use Orchestra\Testbench\TestCase;
use Orchestra\Testbench\Traits\WithLoadMigrationsFrom;

abstract class AbstractTestCase extends TestCase
{
    use WithLoadMigrationsFrom;
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        //$this->loadMigrationsFrom(realpath(__DIR__.'/../src/resources/migrations'));
    }

    public function migrate()
    {
        //$this->loadLaravelMigrations('mysql');

        //$this->artisan('migrate', ['--database' => 'mysql']);
        //$this->artisan('migrate', ['--database' => 'mysql', '--path' => 'migrations']);
        $this->artisan('migrate', ['--database' => 'mysql', '--path' => '../src/resources/migrations/']);
        //$this->artisan('migrate', ['--database' => 'mysql', '--realpath' => realpath(__DIR__.'/../src/resources/migrations')]);

        /**
         * - Verificar o proble do --path (nao esta localizando as migrations)
         * - Descomentar os testes
         */
        //echo 'Realpath '. realpath(__DIR__.'/../src/resources/migrations') . PHP_EOL; die;
//        $this->loadMigrationsFrom([
//            '--database' => 'testing',
//            '--realpath' => realpath(__DIR__.'/../src/resources/migrations'),
//        ]);
        //$this->artisan('migrate', ['--database' => 'mysql', '--path' => '/var/www/src/resources/migrations']);

    }

    /**
     * Define environment setup.
     *
     * @param  \Illuminate\Foundation\Application  $app
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {


//        $app['config']->set('database.default', 'testing');
//        var_dump($app['config']->get('database.connections.mysql')); die;

        // Setup default database to use sqlite :memory:
//        $app['config']->set('database.default', 'testbench');
//        $app['config']->set('database.connections.testbench', [
//            'driver'   => 'sqlite',
//            'database' => ':memory:',
//            'prefix'   => '',
//        ]);
//        var_dump($app['config']['database']['connections']['mysql']);
    }

}